<?php

/**
 * @file
 * Hooks and functions for the OneLogin module.
 */


/**
 * Implements hook_help().
 */
function onelogin_help($path, $arg) {
  switch ($path) {
    case "admin/help#onelogin_saml":
      return '<p>'.  t('Allow Drupal user authentication via OneLogin SAML.') .'</p>';
      break;
  }
}

/**
 * Implements hook_menu()
 */
function onelogin_menu() {
  // Admin configruation form.
  $items['admin/config/people/onelogin'] = array(
    'title' => 'OneLogin',
    'description' => 'Configure OneLogin SAML certs and settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('onelogin_settings_form'),
    'file' => 'includes/onelogin.admin.inc',
    'access arguments' => array('administer onelogin'),
    'type' => MENU_NORMAL_ITEM,
  );

  // SAML consumer callback.
  $items['onelogin_saml/consumer'] = array(
    'title' => 'SAML Consumer',
    'page callback' => 'onelogin_consume',
    'file' => 'includes/onelogin.consume.inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function onelogin_permission() {
  return array(
    'administer onelogin' => array(
      'title' => t('Administer OneLogin'),
      'description' => t('Make configuration changes to the OneLogin module.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function onelogin_libraries_info() {
  $libraries['onelogin'] = array(
    'name' => 'OneLogin SAML PHP',
    'vendor url' => 'https://www.onelogin.com',
    'download url' => 'https://github.com/onelogin/php-saml/releases',
    'version' => '1.0.0',
    'version callback' => 'onelogin_libraries_version',
    'files' => array(
      'php' => array(
        'src/OneLogin/Saml/AuthRequest.php',
        'src/OneLogin/Saml/Metadata.php',
        'src/OneLogin/Saml/Response.php',
        'src/OneLogin/Saml/Settings.php',
        'src/OneLogin/Saml/XmlSec.php',
        'ext/xmlseclibs/xmlseclibs.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Helper function to return OneLogin PHP SAML library version. Necessary
 * because there's no way to determine it from the library itself.
 *
 * @see onelogin_libraries_info()
 */
function onelogin_libraries_get_version($library, $options) {
  return $library['version'];
}
